// <auto-generated />
using JobApplicationHelper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobApplicationHelper.Migrations
{
    [DbContext(typeof(ExperienceBankDbContext))]
    partial class ExperienceBankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("JobApplicationHelper.Data.Entities.ContextEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Contexts");
                });

            modelBuilder.Entity("JobApplicationHelper.Data.Entities.ExperienceContextEntity", b =>
                {
                    b.Property<string>("ExperienceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContextId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExperienceId", "ContextId");

                    b.HasIndex("ContextId");

                    b.ToTable("ExperienceContexts");
                });

            modelBuilder.Entity("JobApplicationHelper.Data.Entities.ExperienceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Organization")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("JobApplicationHelper.Data.Entities.ExperienceEvidenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExperienceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId", "SortOrder");

                    b.ToTable("ExperienceEvidence");
                });

            modelBuilder.Entity("JobApplicationHelper.Data.Entities.ExperienceLinkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExperienceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId", "SortOrder");

                    b.ToTable("ExperienceLinks");
                });

            modelBuilder.Entity("JobApplicationHelper.Data.Entities.ExperienceSkillEntity", b =>
                {
                    b.Property<string>("ExperienceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExperienceId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("ExperienceSkills");
                });

            modelBuilder.Entity("JobApplicationHelper.Data.Entities.SkillEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("JobApplicationHelper.Data.Entities.ExperienceContextEntity", b =>
                {
                    b.HasOne("JobApplicationHelper.Data.Entities.ContextEntity", "Context")
                        .WithMany("Experiences")
                        .HasForeignKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobApplicationHelper.Data.Entities.ExperienceEntity", "Experience")
                        .WithMany("Contexts")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Context");

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("JobApplicationHelper.Data.Entities.ExperienceEvidenceEntity", b =>
                {
                    b.HasOne("JobApplicationHelper.Data.Entities.ExperienceEntity", "Experience")
                        .WithMany("Evidence")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("JobApplicationHelper.Data.Entities.ExperienceLinkEntity", b =>
                {
                    b.HasOne("JobApplicationHelper.Data.Entities.ExperienceEntity", "Experience")
                        .WithMany("Links")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("JobApplicationHelper.Data.Entities.ExperienceSkillEntity", b =>
                {
                    b.HasOne("JobApplicationHelper.Data.Entities.ExperienceEntity", "Experience")
                        .WithMany("Skills")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobApplicationHelper.Data.Entities.SkillEntity", "Skill")
                        .WithMany("Experiences")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("JobApplicationHelper.Data.Entities.ContextEntity", b =>
                {
                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("JobApplicationHelper.Data.Entities.ExperienceEntity", b =>
                {
                    b.Navigation("Contexts");

                    b.Navigation("Evidence");

                    b.Navigation("Links");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("JobApplicationHelper.Data.Entities.SkillEntity", b =>
                {
                    b.Navigation("Experiences");
                });
#pragma warning restore 612, 618
        }
    }
}
